// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBk8kS1QLPaFZuDee5QcXICdUEdbtRZlxI',
    appId: '1:6155605759:web:580128776b90640c271eca',
    messagingSenderId: '6155605759',
    projectId: 'whatsapp--backend-81a7c',
    authDomain: 'whatsapp--backend-81a7c.firebaseapp.com',
    storageBucket: 'whatsapp--backend-81a7c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiFt8ItUZ0D3p6x7DEg0FpScSViIC4R1A',
    appId: '1:6155605759:android:3974c0cd1eb1c890271eca',
    messagingSenderId: '6155605759',
    projectId: 'whatsapp--backend-81a7c',
    storageBucket: 'whatsapp--backend-81a7c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWO_hFxzLY9TKmvAD5_m0q9GwJY2jSkXQ',
    appId: '1:6155605759:ios:030b27134ec8b557271eca',
    messagingSenderId: '6155605759',
    projectId: 'whatsapp--backend-81a7c',
    storageBucket: 'whatsapp--backend-81a7c.appspot.com',
    iosClientId: '6155605759-l3nj918l1gbtk8vq2e01th7nf01ca8ss.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsappUi',
  );
}
